# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "b3e927829c5f74a3d4f2fb448b4eb360"
name = "demoextension"
handle = "demoextension-6"
application_url = "https://select-developing-italia-expenditure.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "checkout-plus-rs.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_customers,read_shipping,write_customers,write_products,write_shipping"

[auth]
redirect_urls = [
  "https://select-developing-italia-expenditure.trycloudflare.com/auth/callback",
  "https://select-developing-italia-expenditure.trycloudflare.com/auth/shopify/callback",
  "https://select-developing-italia-expenditure.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-07"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "https://commitments-museum-tricks-mirror.trycloudflare.com/webhooks"

[pos]
embedded = false
